### ISSUE TITLE
Český slovník bez diakritiky v MS Office

### ISSUE THREAD

**Issue by yogurtcz** [MozillaCZ/cesky_slovnik_pro_kontrolu_pravopisu#12]
Potreboval bych rozbehnout kontrolu ceskeho pravopisu v MS Office. Pri pouziti tady dostupneho cestina.dic vraci prilozenou chybu. Prosim o pomoc.
![1](https://user-images.githubusercontent.com/3358033/67483881-0c4dcb00-f667-11e9-8e32-2168a3832235.PNG)

**Comment by MikkCZ** [comment]
S importem tohoto formátu pro MS Office nemám a zkušenost a není k tomu ani určen. Pokud vím, Office má podporu pro slovníky vlastní.
